### ISSUE TITLE
Update Tesseract for testing

### ISSUE THREAD

**Issue by nok** [madmaze/pytesseract#216]
Hello,

it would be great if we could add the next stable version of Tesseract for testing. In addition we could update the version of the operating system. I mean, why not 😌?

1. Tesseract (current 3.04.01) to 4.1.0 (ppa [~alex-p/+archive/ubuntu/tesseract-ocr](https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr), required)
2. Ubuntu Ubuntu Xenial 16.04 (current) to Bionic 18.04 (optional)

Reasons:
- Unit tests broke in a PR https://github.com/madmaze/pytesseract/pull/215, b/c of an old version of Tesseract and/or Leptonica
- Feature requests like https://github.com/madmaze/pytesseract/issues/172 (related to https://github.com/tesseract-ocr/tesseract/issues/785#issuecomment-451682596) require a newer version of Tesseract

Solution:

We could use Travis to test `pytesseract` with Tesseract-OCR 3.04.01 and 4.1.0 on Bionic 18.04 using a simple Dockerfile. I can do that and create a PR, but in this case it would be great to get some opinions first.

Edit:

Fix and change Xenial version from 14.04 to 16.04.

**Comment by johnthagen** [comment]
FYI, Xenial is 16.04, not 18.04: http://releases.ubuntu.com/16.04/

It does look like Bionic was recently added to Travis CI: https://docs.travis-ci.com/user/reference/bionic/

So it should be as simple as bumping up the `dist: bionic` and making sure everything works.

**Comment by nok** [comment]
Hmm, do we want to support Tesseract 3? If so, we should use Xenial, because it has still prebuilds of Tesseract 3. Otherwise we have to compile it manually or skip this version. In general I prefer the support of both versions 3 and 4.

Image: `ubuntu:bionic`:
```
root@0376b17f81e6:/# apt-cache madison tesseract-ocr
PPA -> tesseract-ocr | 4.1.0-1ppa1~bionic1 | http://ppa.launchpad.net/alex-p/tesseract-ocr/ubuntu bionic/main amd64 Packages
DEF -> tesseract-ocr | 4.00~git2288-10f4998a-2 | http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```
Image `ubuntu:xenial`:
```
root@cea4bffed83f:/# apt-cache madison tesseract-ocr
PPA -> tesseract-ocr | 4.1.0-1ppa1~xenial1 | http://ppa.launchpad.net/alex-p/tesseract-ocr/ubuntu xenial/main amd64 Packages
DEF -> tesseract-ocr |  3.04.01-4 | http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
```

Yes, we can try to avoid a Docker image by using further environment variables. The following configuration is a simple draft to demonstrate the idea how to run the unit tests against Tesseract 3 and 4:

```
language: python

dist: xenial

matrix:
    include:
      - python: 2.7
        env: TOXENV=py27 TESSERACT_VERSION=3.04.01-4
      - python: 3.5
        env: TOXENV=py35 TESSERACT_VERSION=3.04.01-4
      - python: 3.6
        env: TOXENV=py36 TESSERACT_VERSION=3.04.01-4
      - python: 3.7
        env: TOXENV=py37 TESSERACT_VERSION=3.04.01-4
      - python: 3.7
        env: TOXENV=pep8 TESSERACT_VERSION=3.04.01-4
      - python: 2.7
        env: TOXENV=py27 TESSERACT_VERSION=4.1.0-1ppa1~xenial1
      - python: 3.5
        env: TOXENV=py35 TESSERACT_VERSION=4.1.0-1ppa1~xenial1
      - python: 3.6
        env: TOXENV=py36 TESSERACT_VERSION=4.1.0-1ppa1~xenial1
      - python: 3.7
        env: TOXENV=py37 TESSERACT_VERSION=4.1.0-1ppa1~xenial1
      - python: 3.7
        env: TOXENV=pep8 TESSERACT_VERSION=4.1.0-1ppa1~xenial1

before_install:
  - sudo apt-get update
  - install -y software-properties-common
  - add-apt-repository -y ppa:alex-p/tesseract-ocr
  - sudo apt-get update
  - sudo apt-get install -y tesseract-ocr=${TESSERACT_VERSION}
  - sudo apt-get install -y tesseract-ocr-fra

install:
  pip install tox

script:
  tox

notifications:
  email: false
```

**Comment by johnthagen** [comment]
What if instead of a custom PPA, we put both xenial and bionic in the `matrix` and use their native `tesseract`. Would that cover v3 and v4? That seems like a simple first step.

**Comment by nok** [comment]
It's a good idea, but I have never seen a configuration where the distribution is configured by an environment variable form a matrix. And I couldn't find any informations about that.

**Comment by johnthagen** [comment]
Perhaps this?

https://docs.travis-ci.com/user/multi-os/#example-multi-os-build-matrix

```yaml
matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode7.2
```

Maybe we could do something like:

```yaml
matrix:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
```

**Comment by nok** [comment]
That looks good! But do we have to combine these?

```
language: python

matrix:
    include:
      - os: linux
        dist: xenial
        python: 2.7
        env: TOXENV=py27
      - os: linux
        dist: xenial
        python: 3.5
        env: TOXENV=py35
      - os: linux
        dist: xenial
        python: 3.6
        env: TOXENV=py36
      - os: linux
        dist: xenial
        python: 3.7
        env: TOXENV=py37
      - os: linux
        dist: xenial
        python: 3.7
        env: TOXENV=pep8
      - os: linux
        dist: bionic
        python: 2.7
        env: TOXENV=py27
      - os: linux
        dist: bionic
        python: 3.5
        env: TOXENV=py35
      - os: linux
        dist: bionic
        python: 3.6
        env: TOXENV=py36
      - os: linux
        dist: bionic
        python: 3.7
        env: TOXENV=py37
      - os: linux
        dist: bionic
        python: 3.7
        env: TOXENV=pep8

before_install:
  - sudo apt-get install -y tesseract-ocr
  - sudo apt-get install -y tesseract-ocr-fra

install:
  pip install tox

script:
  tox

notifications:
  email: false
```
Can you try it out on a separate branch? Travis will checkout this new branch and run the tests.
